/*
 * @Description:
 * @Usage:
 * @Author: richen
 * @Date: 2021-12-01 14:27:47
 * @LastEditTime: 2023-01-10 16:56:58
 */
import type globby from "globby";
import fs from "fs";
import path from "path";
import { createHash } from "crypto";

/** Default glob patterns: JS/TS files, excluding declaration files */
const DEFAULT_PATTERN = ["**/**.js", "**/**.ts", "!**/**.d.ts"] as const;

/** Default ignore patterns for safety and performance */
const DEFAULT_IGNORE = [
    "**/node_modules/**",
    "**/logs/**",
    "**/static/**",
] as const;

/** Cache schema version: bump to invalidate every existing cache file. */
const SCAN_CACHE_VERSION = 2;

/** Cache file, relative to the scan base dir (i.e. cwd). */
const SCAN_CACHE_FILE = path.join(".koatty", "scan-cache.json");

/** One cached scan result. */
interface ScanCacheEntry {
    /** Membership and per-file state, excluding the cache itself. */
    fingerprint: string;
    /** the globby result (file names relative to the scan root) */
    files: string[];
}

interface ScanCache {
    version: number;
    entries: Record<string, ScanCacheEntry>;
}

/** Result item for each loaded file. */
export interface ResInterface {
    name: string;
    path: string;
    target: any;
}

/** Callback invoked for each loaded file: (fileName, filePath, exportedTarget) */
export type callbackFunc = (fileName: string, xpath: string, target: any) => void;

/** Optional behavior switches; every field is optional so the old API stays valid. */
export interface LoadOptions {
    /**
     * Reuse `.koatty/scan-cache.json` to skip `globby` when nothing changed.
     * Default: true. Also disabled by `KOATTY_DISABLE_SCAN_CACHE=1`.
     */
    scanCache?: boolean;
    /** Override the cache file location (mainly for tests). */
    cacheFile?: string;
    /** Optional production manifest generated by koatty manifest --runtime-dir. */
    manifestFile?: string;
}

/**
 * Load modules from directories by glob pattern.
 *
 * @param loadDir - Directories to load (relative to baseDir or absolute)
 * @param baseDir - Base directory; defaults to process.cwd()
 * @param fn - Optional callback per file
 * @param pattern - Glob patterns; defaults to JS/TS excluding .d.ts
 * @param ignore - Glob ignore patterns; defaults to node_modules, logs, static
 * @param options - Optional PERF-03 scan cache switches
 * @returns Array of `\{ name, path, target \}` for each loaded file
 */
export function Load(
    loadDir: string[],
    baseDir?: string,
    fn?: callbackFunc,
    pattern: string[] = [...DEFAULT_PATTERN],
    ignore: string[] = [...DEFAULT_IGNORE],
    options: LoadOptions = {}
): ResInterface[] {
    const base = path.resolve(baseDir ?? process.cwd());
    const loadDirs = Array.isArray(loadDir) ? loadDir : [loadDir];
    const res: ResInterface[] = [];

    // PERF-03: scan result cache (`<base>/.koatty/scan-cache.json`)
    const manifest = options.manifestFile ? readRuntimeManifest(base, options.manifestFile) : undefined;
    const store = manifest ? undefined : resolveScanCache(base, options);

    for (let dir of loadDirs) {
        dir = buildLoadDir(base, dir); // SEC-16: never escapes `base`
        const entryKey = `${dir}::${SCAN_CACHE_VERSION}|${pattern.join(",")}|${ignore.join(",")}`;
        const fileResults = manifest ? selectManifestFiles(dir, manifest, pattern, ignore) : scanDir(dir, pattern, ignore, entryKey, store);

        for (const name of fileResults) {
            const file = checkedPath(base, path.join(dir, name));
            const baseName = path.basename(name);
            const lastDot = baseName.lastIndexOf(".");
            const fileName = lastDot > -1 ? baseName.slice(0, lastDot) : baseName;

            const target = requireDefault(file);
            if (fn) {
                fn(fileName, file, target);
            }
            res.push({ name: fileName, path: file, target });
        }
    }

    // Persist the cache after the scan (atomic write, never throws).
    if (store) {
        writeScanCache(store);
    }

    return res;
}

/**
 * Resolve a load directory against `base`.
 *
 * SEC-16: the resolved path must stay inside `base`. Absolute paths outside the
 * project and `../` traversal are rejected before loading any module.
 */
function checkedPath(base: string, candidate: string): string {
    const root = fs.realpathSync(base);
    const resolved = fs.realpathSync(candidate);
    const relative = path.relative(root, resolved);
    if (relative === '..' || relative.startsWith(`..${path.sep}`) || path.isAbsolute(relative)) {
        throw new Error(`Load path escapes baseDir: ${candidate}`);
    }
    return resolved;
}
export function buildLoadDir(baseDir: string, dir: string): string {
    const base = path.resolve(baseDir);
    const candidate = path.resolve(base, dir);
    const relative = path.relative(base, candidate);
    if (relative === '..' || relative.startsWith(`..${path.sep}`) || path.isAbsolute(relative)) throw new Error(`Load path escapes baseDir: ${dir}`);
    return checkedPath(base, candidate);
}

/**
 * SEC-16: report paths relative to `base`, so absolute host paths outside the
 * project are never logged or returned.
 */
export function toSafePath(baseDir: string, target: string): string {
    const relative = path.relative(path.resolve(baseDir), path.resolve(target));
    if (!relative || relative.startsWith("..") || path.isAbsolute(relative)) {
        return path.basename(target);
    }
    return relative;
}

/** Scan one directory, reusing the cache entry when nothing changed. */
function scanDir(
    dir: string,
    pattern: string[],
    ignore: string[],
    entryKey: string,
    store: ScanStore | undefined
): string[] {
    const cached = store?.cache.entries[entryKey];
    if (cached && store && isCacheFresh(dir, cached, store.file, ignore)) {
        return cached.files;
    }

    // Do not load glob traversal dependencies on the production manifest path.
    // Synchronous Load API requires lazy CommonJS loading here.
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const imported = require("globby");
    const glob = (imported.default ?? imported) as typeof globby;
    const files = glob.sync(pattern, { cwd: dir, ignore });
    if (store) {
        const state = treeState(dir, store.file, ignore);
        store.cache.entries[entryKey] = {
            fingerprint: state,
            files,
        };
    }
    return files;
}

/**
 * A cache entry is fresh when no directory under the scan root changed and every
 * cached file still exists with an unchanged mtime (catches edits and deletions).
 */
function isCacheFresh(dir: string, entry: ScanCacheEntry, cacheFile: string, ignore: string[]): boolean {
    try {
        if (treeState(dir, cacheFile, ignore) !== entry.fingerprint) return false;
        for (const name of entry.files) {
            if (typeof name !== 'string' || path.isAbsolute(name)) return false;
            checkedPath(dir, path.resolve(dir, name));
        }
        return true;
    } catch { return false; }
}

/** Fingerprint membership and individual timestamps, including old-mtime additions. */
function treeState(dir: string, cacheFile: string, ignore: string[]): string {
    const hash = createHash('sha256');
    const cache = cacheFile ? path.join(fs.realpathSync(path.dirname(cacheFile)), path.basename(cacheFile)) : '';
    const visited = new Set<string>();
    const walk = (current: string) => {
        const real = checkedPath(dir, current);
        if (visited.has(real)) return;
        visited.add(real);
        for (const entry of fs.readdirSync(current, { withFileTypes: true }).sort((a,b) => a.name.localeCompare(b.name))) {
            const full = path.join(current, entry.name);
            if (full === cache || (path.dirname(full) === path.dirname(cache) && entry.name.startsWith('.scan-cache.'))) continue;
            if (entry.isDirectory() && ignore.includes(`**/${entry.name}/**`)) continue;
            // Do not follow symlinks while fingerprinting. Selected modules are checked again before require.
            const stat = fs.lstatSync(full);
            hash.update(JSON.stringify([path.relative(dir, full), stat.isDirectory() ? 'dir' : 'file', stat.isDirectory() ? 0 : stat.mtimeMs, stat.isDirectory() ? 0 : stat.size]));
            if (entry.isDirectory()) walk(full);
            else if (entry.isSymbolicLink()) {
                const linked = checkedPath(dir, full);
                if (fs.statSync(linked).isDirectory()) walk(full);
                else { const file = fs.statSync(linked); hash.update(JSON.stringify([linked, file.mtimeMs, file.size])); }
            }
        }
    };
    walk(dir);
    return hash.digest('hex');
}

/** Holds the in-memory cache plus the file it is persisted to. */
interface ScanStore {
    cache: ScanCache;
    file: string;
}

/**
 * Persist the cache atomically (temp file in the same directory, then rename).
 * Never throws: an unwritable or missing cache directory simply means the next
 * load scans again.
 */
function writeScanCache(store: ScanStore): void {
    try {
        const dir = path.dirname(store.file);
        fs.mkdirSync(dir, { recursive: true });
        const tmp = path.join(dir, `.scan-cache.${process.pid}.${Date.now()}.tmp`);
        fs.writeFileSync(tmp, JSON.stringify(store.cache), "utf8");
        fs.renameSync(tmp, store.file);
    } catch {
        /* cache is best effort only */
    }
}

/**
 * Resolve the cache holder; returns undefined when the cache is disabled (option
 * or `KOATTY_DISABLE_SCAN_CACHE=1`). The file is read here, before any directory
 * is scanned.
 */
function resolveScanCache(base: string, options: LoadOptions): ScanStore | undefined {
    if (options.scanCache === false) return undefined;
    if (process.env.KOATTY_DISABLE_SCAN_CACHE === "1") return undefined;
    const file = options.cacheFile
        ? path.resolve(options.cacheFile)
        : path.join(base, SCAN_CACHE_FILE);
    try { fs.mkdirSync(path.dirname(file), { recursive: true }); } catch { return undefined; }
    return { cache: readScanCache(file), file };
}

/**
 * Read the cache file. Any error - missing file, invalid JSON, foreign schema -
 * falls back to an empty cache: a corrupt cache must never break startup.
 */
function readScanCache(file: string): ScanCache {
    const empty: ScanCache = { version: SCAN_CACHE_VERSION, entries: {} };
    let parsed: ScanCache;
    try {
        parsed = JSON.parse(fs.readFileSync(file, "utf8")) as ScanCache;
    } catch {
        return empty;
    }
    if (!parsed || parsed.version !== SCAN_CACHE_VERSION || !parsed.entries
        || typeof parsed.entries !== "object") {
        return empty;
    }
    for (const [key, entry] of Object.entries(parsed.entries)) {
        const valid = entry && Array.isArray(entry.files)
            && entry.files.every(f => typeof f === "string") && typeof entry.fingerprint === "string";
        if (!valid) {
            delete parsed.entries[key];
        }
    }
    return parsed;
}

/**
 * es5/6 require
 *
 * @export
 * @param {string} p
 * @returns
 */
function requireDefault(p: string) {
    /* eslint-disable global-require, @typescript-eslint/no-require-imports */
    const ex = require(p);
    return (ex && (typeof ex === "object") && "default" in ex) ? ex.default : ex;
}


interface RuntimeFiles { root: string; files: string[]; }

/** A manifest is an explicit immutable deployment inventory, not a scan cache. */
function readRuntimeManifest(base: string, filename: string): RuntimeFiles | undefined {
    const file = checkedPath(base, path.resolve(base, filename));
    const document = JSON.parse(fs.readFileSync(file, 'utf8'));
    // Static AI manifests have no executable inventory and keep normal scanning.
    if (!Object.prototype.hasOwnProperty.call(document, 'runtime')) return undefined;
    const runtime = document.runtime;
    if (!runtime || runtime.version !== 1 || typeof runtime.root !== 'string' || !Array.isArray(runtime.files)) {
        throw new Error('Invalid runtime manifest schema');
    }
    if (path.isAbsolute(runtime.root)) throw new Error('Runtime manifest root must be relative');
    const root = buildLoadDir(base, runtime.root);
    const files: string[] = [];
    const seen = new Set<string>();
    // Validate the complete inventory before executing the first application module.
    for (const entry of runtime.files) {
        if (!entry || typeof entry.file !== 'string' || path.isAbsolute(entry.file)
            || !/\.(?:c?js)$/.test(entry.file) || !/^[a-f0-9]{64}$/.test(entry.sha256)) {
            throw new Error('Invalid runtime manifest file entry');
        }
        const absolute = buildLoadDir(root, entry.file);
        if (seen.has(absolute)) throw new Error('Duplicate runtime manifest file');
        seen.add(absolute);
        if (createHash('sha256').update(fs.readFileSync(absolute)).digest('hex') !== entry.sha256) {
            throw new Error(`Runtime manifest file changed: ${entry.file}`);
        }
        files.push(absolute);
    }
    return {root, files};
}

function selectManifestFiles(dir: string, manifest: RuntimeFiles, pattern: string[], ignore: string[]): string[] {
    const relative = path.relative(manifest.root, dir);
    if (relative === '..' || relative.startsWith(`..${path.sep}`) || path.isAbsolute(relative)) {
        throw new Error('Component scan directory is not covered by the runtime manifest');
    }
    const match = require('picomatch') as (patterns: string[], options?: {dot?: boolean}) => (name: string) => boolean;
    const positive = pattern.filter(p => !p.startsWith('!'));
    const excluded = [...ignore, ...pattern.filter(p => p.startsWith('!')).map(p => p.slice(1))];
    const include = match(positive);
    const exclude = excluded.length ? match(excluded, {dot:true}) : () => false;
    return manifest.files.map(file => path.relative(dir, file).split(path.sep).join('/'))
        .filter(name => name !== '..' && !name.startsWith('../') && include(name) && !exclude(name));
}
